var options = [
{"value":"Ruta Nacional Nº8 (altura en Km.)", "label":"Ruta Nacional Nº8 (altura en Km.)"},
{"value":"12 De Octubre", "label":"12 De Octubre"},
{"value":"A. Cementerio", "label":"A. Cementerio"},
{"value":"A. del Valle", "label":"A. del Valle"},
{"value":"A. Dowling", "label":"A. Dowling"},
{"value":"Alfredo Palacios", "label":"Alfredo Palacios"},
{"value":"Alicia Moreau de Justo", "label":"Alicia Moreau de Justo"},
{"value":"Almafuerte", "label":"Almafuerte"},
{"value":"Alsina", "label":"Alsina"},
{"value":"Ameghino", "label":"Ameghino"},
{"value":"América", "label":"América"},
{"value":"Antártida Argentina", "label":"Antártida Argentina"},
{"value":"Av. 29 de Junio", "label":"Av. 29 de Junio"},
{"value":"Av. Alem", "label":"Av. Alem"},
{"value":"Av. Mitre", "label":"Av. Mitre"},
{"value":"Av. Pte. Perón", "label":"Av. Pte. Perón"},
{"value":"Av. Rivadavia", "label":"Av. Rivadavia"},
{"value":"Av. Roque Saenz Peña", "label":"Av. Roque Saenz Peña"},
{"value":"Av. San Martín", "label":"Av. San Martín"},
{"value":"Avellaneda", "label":"Avellaneda"},
{"value":"Bandera Bonaerense", "label":"Bandera Bonaerense"},
{"value":"Barros", "label":"Barros"},
{"value":"Belgrano", "label":"Belgrano"},
{"value":"Buenos Aires", "label":"Buenos Aires"},
{"value":"C. Fosatti", "label":"C. Fosatti"},
{"value":"C. Saavedra", "label":"C. Saavedra"},
{"value":"C. Urioste", "label":"C. Urioste"},
{"value":"Cabo Fregotte - La Luisa", "label":"Cabo Fregotte - La Luisa"},
{"value":"Cahuané", "label":"Cahuané"},
{"value":"Camino de circunvalación", "label":"Camino de circunvalación"},
{"value":"Cardenal Samore", "label":"Cardenal Samore"},
{"value":"Catamarca", "label":"Catamarca"},
{"value":"Centenario", "label":"Centenario"},
{"value":"Chaco", "label":"Chaco"},
{"value":"Chubut", "label":"Chubut"},
{"value":"Colón", "label":"Colón"},
{"value":"Colón - La Luisa", "label":"Colón - La Luisa"},
{"value":"Constitución", "label":"Constitución"},
{"value":"Cordoba", "label":"Cordoba"},
{"value":"Corrientes", "label":"Corrientes"},
{"value":"D. Bojanich", "label":"D. Bojanich"},
{"value":"D. Faustino Sarmiento", "label":"D. Faustino Sarmiento"},
{"value":"D. Fidel Sarmiento", "label":"D. Fidel Sarmiento"},
{"value":"D. Rocha", "label":"D. Rocha"},
{"value":"Dean Funes - La Luisa", "label":"Dean Funes - La Luisa"},
{"value":"Dr. Bavio", "label":"Dr. Bavio"},
{"value":"Dr. R. Favaloro", "label":"Dr. R. Favaloro"},
{"value":"Dr. Yanzi Molina", "label":"Dr. Yanzi Molina"},
{"value":"Dr. Yordán", "label":"Dr. Yordán"},
{"value":"E. Bacca", "label":"E. Bacca"},
{"value":"E. Duarte", "label":"E. Duarte"},
{"value":"Entre Rios", "label":"Entre Rios"},
{"value":"España", "label":"España"},
{"value":"Esteban Dalio", "label":"Esteban Dalio"},
{"value":"Formosa", "label":"Formosa"},
{"value":"G. Brown", "label":"G. Brown"},
{"value":"G. Gómez", "label":"G. Gómez"},
{"value":"G. Lucotti", "label":"G. Lucotti"},
{"value":"Gardel", "label":"Gardel"},
{"value":"H. Di Fulvio", "label":"H. Di Fulvio"},
{"value":"H. Irigoyen", "label":"H. Irigoyen"},
{"value":"I. Malvinas", "label":"I. Malvinas"},
{"value":"Independencia", "label":"Independencia"},
{"value":"Int.Horacio Tapia", "label":"Int.Horacio Tapia"},
{"value":"Italia", "label":"Italia"},
{"value":"J. Apaolaza", "label":"J. Apaolaza"},
{"value":"J. B. Justo", "label":"J. B. Justo"},
{"value":"J. M. de Rosas", "label":"J. M. de Rosas"},
{"value":"J. Newbery", "label":"J. Newbery"},
{"value":"José Mármol", "label":"José Mármol"},
{"value":"Jujuy", "label":"Jujuy"},
{"value":"La Pampa", "label":"La Pampa"},
{"value":"La Plata", "label":"La Plata"},
{"value":"La Rioja", "label":"La Rioja"},
{"value":"Las Calandrias", "label":"Las Calandrias"},
{"value":"Las Gaviotas", "label":"Las Gaviotas"},
{"value":"Las Martinetas", "label":"Las Martinetas"},
{"value":"Las Perdices", "label":"Las Perdices"},
{"value":"Los Granaderos", "label":"Los Granaderos"},
{"value":"Los Horneros", "label":"Los Horneros"},
{"value":"Los Patos", "label":"Los Patos"},
{"value":"Los Zorzales", "label":"Los Zorzales"},
{"value":"M. Güemes", "label":"M. Güemes"},
{"value":"M.Jelicich", "label":"M.Jelicich"},
{"value":"Maria Azucena Lobo O´connor", "label":"Maria Azucena Lobo O´connor"},
{"value":"Mendoza", "label":"Mendoza"},
{"value":"Misiones", "label":"Misiones"},
{"value":"Moreno", "label":"Moreno"},
{"value":"Nelson Mandela", "label":"Nelson Mandela"},
{"value":"Neuquen", "label":"Neuquen"},
{"value":"O. Allende", "label":"O. Allende"},
{"value":"P. Demergasso", "label":"P. Demergasso"},
{"value":"P. Lacabe", "label":"P. Lacabe"},
{"value":"P. Neruda", "label":"P. Neruda"},
{"value":"Padre Mugica", "label":"Padre Mugica"},
{"value":"Pedro Gambaro", "label":"Pedro Gambaro"},
{"value":"Pellegrini - La Luisa", "label":"Pellegrini - La Luisa"},
{"value":"Prolongación futura calle San Juan", "label":"Prolongación futura calle San Juan"},
{"value":"Pte. S. M. Allende", "label":"Pte. S. M. Allende"},
{"value":"Rio Negro", "label":"Rio Negro"},
{"value":"Salamero", "label":"Salamero"},
{"value":"Salta", "label":"Salta"},
{"value":"San Juan", "label":"San Juan"},
{"value":"San Luis", "label":"San Luis"},
{"value":"Santa Cruz", "label":"Santa Cruz"},
{"value":"Santa Fe", "label":"Santa Fe"},
{"value":"Sgo. del Estero", "label":"Sgo. del Estero"},
{"value":"Spinetta", "label":"Spinetta"},
{"value":"Tierra del Fuego", "label":"Tierra del Fuego"},
{"value":"Touron Montero", "label":"Touron Montero"},
{"value":"Tucumán", "label":"Tucumán"},
{"value":"Vte. López y Planes", "label":"Vte. López y Planes"},
{"value":"Vuelta de Obligado", "label":"Vuelta de Obligado"},
{"value":"Yapeyú", "label":"Yapeyú"}
]

export default options;